from tkinter import *
import tkinter as tk
from tkinter import messagebox
root = Tk() 
root.geometry("980x650")
root.title("Car Rental Reciept" )

#Creating Form
title = Label(root,text="CAR RENTAL RECEIPT",font=("Calibri Bold",30),anchor=N).grid(row=0,column=2)
date = Label(root,text="DATE ").grid(row=3,column=0)
date = Entry(root)
date.grid(row=3,column=1)
receipt = Label(root,text="RECEIPT# ").grid(row=3,column=3)
receipt = Entry(root)
receipt.grid(row=3,column=4)
subhd1 = Label(root,text="COMPANY INFO",font=("Calibri Bold",16)).grid(row=7,column=1)
company = Label(root,text="COMPANY ").grid(row=9,column=0)
company = Entry(root)
company.grid(row=9,column=1)
rep = Label(root,text="REPRESENTATIVE").grid(row=10,column=0)
rep = Entry(root)
rep.grid(row=10,column=1)
loc = Label(root,text="LOCATION").grid(row=11,column=0)
loc = Entry(root)
loc.grid(row=11,column=1)
csz = Label(root,text="CITY/STATE/ZIP").grid(row=12,column=0)
csz = Entry(root)
csz.grid(row=12,column=1)
phone = Label(root,text="PHONE").grid(row=13,column=0)
phone = Entry(root)
phone.grid(row=13,column=1)
subhd2 = Label(root,text="LESSEE INFO",font=("Calibri Bold",16)).grid(row=7,column=4)
name = Label(root,text="NAME").grid(row=9,column=3)
name = Entry(root)
name.grid(row=9,column=4)
license = Label(root,text="LICENSE#").grid(row=10,column=3)
license = Entry(root)
license.grid(row=10,column=4)
address = Label(root,text="ADDRESS").grid(row=11,column=3)
address = Entry(root)
address.grid(row=11,column=4)
csz1 = Label(root,text="CITY/STATE/ZIP").grid(row=12,column=3)
csz1 = Entry(root)
csz1.grid(row=12,column=4)
phone1 = Label(root,text="PHONE").grid(row=13,column=3)
phone1 = Entry(root)
phone1.grid(row=13,column=4)
V = Label(root,text="VEHICLE INFORMATION",font=("Calibri Bold",26)).grid(row=16,column=2)
VIN1 = Label(root,text="VIN").grid(row=18,column=0)
VIN1 = Entry(root)
VIN1.grid(row=18,column=1)
make = Label(root,text="MAKE").grid(row=19,column=0)
make = Entry(root)
make.grid(row=19,column=1)
year = Label(root,text="YEAR").grid(row=20,column=0)
year = Entry(root)
year.grid(row=20,column=1)
color = Label(root,text="COLOR").grid(row=21,column=0)
color = Entry(root)
color.grid(row=21,column=1)
reg = Label(root,text="REGISTRATION#").grid(row=18,column=3)
reg = Entry(root)
reg.grid(row=18,column=4)
model = Label(root,text="MODEL").grid(row=19,column=3)
model = Entry(root)
model.grid(row=19,column=4)
milg = Label(root,text="MILEAGE").grid(row=20,column=3)
milg = Entry(root)
milg.grid(row=20,column=4)
VIN = Label(root,text="VIN",font=("Calibri Bold",16)).grid(row=50,column=0)
cd = Label(root,text="COST/DAY",font=("Calibri Bold",16)).grid(row=50,column=1)
of = Label(root,text="OF DAYS#",font=("Calibri Bold",16)).grid(row=50,column=2)
ac = Label(root,text="ADDITIONAL COST",font=("Calibri Bold",16)).grid(row=50,column=3)
lc = Label(root,text="LINE COST",font=("Calibri Bold",16)).grid(row=50,column=4)
pm = Label(root,text="PAYMENT METHOD",font=("Calibri Bold",14)).grid(row=57,column=0)
st = Label(root,text="SUBTOTAL",font=("Calibri",14)).grid(row=58,column=2)
st = Entry(root).grid(row=58,column=3)
tax= Label(root,text="TAX(5%)",font=("Calibri",12)).grid(row=59,column=2)
tax = Entry(root)
tax.grid(row=59,column=3)
total= Label(root,text="TOTAL",font=("Calibri",12)).grid(row=60,column=2)
total= Entry(root)
total.grid(row=60,column=3)
ap = Label(root,text="AMOUNT PAID",font=("Calibri",12)).grid(row=61,column=2)
ap = Entry(root)
ap.grid(row=61,column=3)
sig = Label(root,text="AUTHORIZED SIGNATURE",font=("Calibri",12)).grid(row=62,column=3)
sig = Entry(root)
sig.grid(row=62,column=4)
rp_name = Label(root,text="REPRESENTATIVE NAME",font=("Calibri",12)).grid(row=63,column=3)
rp_name = Entry(root)
rp_name.grid(row=63,column=4)
a=Checkbutton(root,text="CASH",font=("Calibri",12)).grid(row=58,column=0)
b=Checkbutton(root,text="DEBIT",font=("Calibri",12)).grid(row=59,column=0)
c=Checkbutton(root,text="CREDIT",font=("Calibri",12)).grid(row=60,column=0)
d=Checkbutton(root,text="OTHER",font=("Calibri",12)).grid(row=61,column=0)
cash=Entry(root)
cash.grid(row=58,column=1)
deb=Entry(root)
deb.grid(row=59,column=1)
cred=Entry(root)
cred.grid(row=60,column=1)
oth=Entry(root)
oth.grid(row=61,column=1)
e=Entry(root)
e.grid(row=51,column=0)
f=Entry(root)
f.grid(row=52,column=0)
g=Entry(root)
g.grid(row=53,column=0)
h=Entry(root)
h.grid(row=51,column=1)
i=Entry(root)
i.grid(row=52,column=1)
j=Entry(root)
j.grid(row=53,column=1)
k=Entry(root)
k.grid(row=51,column=2)
l=Entry(root)
l.grid(row=52,column=2)
m=Entry(root)
m.grid(row=53,column=2)
n=Entry(root)
n.grid(row=51,column=3)
o=Entry(root)
o.grid(row=52,column=3)
p=Entry(root)
p.grid(row=53,column=3)
q=Entry(root)
q.grid(row=51,column=4)
r=Entry(root)
r.grid(row=52,column=4)
s=Entry(root)
s.grid(row=53,column=4)
msg=Button(root, text='SUBMIT',width=20,bg='grey').grid(row=63,column=2)
root.mainloop()
